<?php

declare(strict_types=1);

namespace Zhortein\MultiTenantBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\Config\Definition\Exception\InvalidConfigurationException;
use Zhortein\MultiTenantBundle\Messenger\MessengerRoutingStrategy;

/**
 * Configuration definition for the multi-tenant bundle.
 *
 * This class defines the configuration tree structure and default values
 * for the bundle's configuration options.
 */
final class Configuration implements ConfigurationInterface
{
    /**
     * @return TreeBuilder<'array'>
     */
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('zhortein_multi_tenant');

        $treeBuilder->getRootNode()
            ->beforeNormalization()
                ->ifTrue(static fn (mixed $value): bool => is_array($value) && array_key_exists('resolution', $value))
                ->then(static function (mixed $value): never {
                    throw new InvalidConfigurationException('The "resolution" option has never been supported. Use the scalar "resolver: path" syntax instead.');
                })
            ->end()
            ->children()
                // Tenant entity configuration
                ->scalarNode('tenant_entity')
                    ->defaultValue('App\\Entity\\Tenant')
                    ->info('The fully qualified class name of your tenant entity')
                ->end()

                // Tenant resolver configuration
                ->enumNode('resolver')
                    ->beforeNormalization()
                        ->ifArray()
                        ->then(static function (mixed $value): never {
                            throw new InvalidConfigurationException('The "resolver" option must be a scalar. Use "resolver: path" instead of the unsupported "resolver.type" structure.');
                        })
                    ->end()
                    ->values(['path', 'subdomain', 'header', 'query', 'domain', 'hybrid', 'dns_txt', 'chain', 'custom'])
                    ->defaultValue('path')
                    ->info('The tenant resolution strategy to use')
                ->end()

                // Resolver chain configuration
                ->arrayNode('resolver_chain')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('order')
                            ->enumPrototype()
                                ->values(['path', 'subdomain', 'header', 'query', 'domain', 'hybrid', 'dns_txt'])
                            ->end()
                            ->defaultValue(['subdomain', 'path', 'header', 'query'])
                            ->info('Order of resolvers to try in the chain')
                        ->end()
                        ->booleanNode('strict')
                            ->defaultTrue()
                            ->info('Whether to use strict mode (throw exceptions on failure/ambiguity)')
                        ->end()
                        ->arrayNode('header_allow_list')
                            ->scalarPrototype()->end()
                            ->defaultValue(['X-Tenant-Id', 'X-Tenant-Slug'])
                            ->info('List of allowed header names for header resolvers')
                        ->end()
                    ->end()
                ->end()

                // Default tenant configuration
                ->scalarNode('default_tenant')
                    ->defaultNull()
                    ->info('Default tenant slug to use when no tenant is resolved')
                ->end()

                // Require tenant configuration
                ->booleanNode('require_tenant')
                    ->defaultFalse()
                    ->info('Whether to require a tenant for all requests')
                ->end()

                // Subdomain resolver configuration
                ->arrayNode('subdomain')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('base_domain')
                            ->defaultValue('localhost')
                            ->info('The base domain for subdomain resolution')
                        ->end()
                        ->arrayNode('excluded_subdomains')
                            ->scalarPrototype()->end()
                            ->defaultValue(['www', 'api', 'admin', 'mail', 'ftp'])
                            ->info('Subdomains to exclude from tenant resolution')
                        ->end()
                    ->end()
                ->end()

                // Header resolver configuration
                ->arrayNode('header')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('name')
                            ->defaultValue('X-Tenant-Slug')
                            ->info('HTTP header name to use for tenant resolution')
                        ->end()
                    ->end()
                ->end()

                // Query resolver configuration
                ->arrayNode('query')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('parameter')
                            ->defaultValue('tenant')
                            ->info('Query parameter name to use for tenant resolution')
                        ->end()
                    ->end()
                ->end()

                // Domain resolver configuration
                ->arrayNode('domain')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('domain_mapping')
                            ->normalizeKeys(false)
                            ->useAttributeAsKey('domain')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                            ->info('Mapping of full domains to tenant slugs (e.g., tenant-one.com: tenant_one)')
                        ->end()
                    ->end()
                ->end()

                // Hybrid resolver configuration
                ->arrayNode('hybrid')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('domain_mapping')
                            ->normalizeKeys(false)
                            ->useAttributeAsKey('domain')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                            ->info('Mapping of full domains to tenant slugs (e.g., acme-client.com: acme)')
                        ->end()
                        ->arrayNode('subdomain_mapping')
                            ->normalizeKeys(false)
                            ->useAttributeAsKey('pattern')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                            ->info('Mapping of domain patterns to resolution strategies (e.g., *.my_platform.com: use_subdomain_as_slug)')
                        ->end()
                        ->arrayNode('excluded_subdomains')
                            ->scalarPrototype()->end()
                            ->defaultValue(['www', 'api', 'admin', 'mail', 'ftp', 'cdn', 'static'])
                            ->info('Subdomains to exclude from tenant resolution')
                        ->end()
                    ->end()
                ->end()

                // DNS TXT resolver configuration
                ->arrayNode('dns_txt')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('timeout')
                            ->defaultValue(5)
                            ->min(1)
                            ->max(30)
                            ->info('DNS query timeout in seconds')
                        ->end()
                        ->booleanNode('enable_cache')
                            ->defaultTrue()
                            ->info('Whether to enable DNS result caching for performance')
                        ->end()
                    ->end()
                ->end()

                // Database configuration
                ->arrayNode('database')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('strategy')
                            ->values(['shared_db', 'multi_db'])
                            ->defaultValue('shared_db')
                            ->info('Database strategy: shared_db (single database with tenant_id filtering) or multi_db (separate databases per tenant)')
                        ->end()
                        ->booleanNode('enable_filter')
                            ->defaultTrue()
                            ->info('Whether to enable the Doctrine tenant filter (shared_db mode only)')
                        ->end()
                        ->booleanNode('auto_tenant_id')
                            ->defaultTrue()
                            ->info('Automatically add tenant_id to entities with #[AsTenantAware] (shared_db mode only)')
                        ->end()
                        ->scalarNode('connection_prefix')
                            ->defaultValue('tenant_')
                            ->info('Connection name prefix for multi_db mode (e.g., tenant_acme)')
                        ->end()
                        ->arrayNode('rls')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultFalse()
                                    ->info('Enable PostgreSQL Row-Level Security (RLS) for defense-in-depth (shared_db mode only)')
                                ->end()
                                ->scalarNode('session_variable')
                                    ->defaultValue('app.tenant_id')
                                    ->info('PostgreSQL session variable name to store current tenant ID')
                                ->end()
                                ->scalarNode('policy_name_prefix')
                                    ->defaultValue('tenant_isolation')
                                    ->info('Prefix for RLS policy names')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                // Cache configuration
                ->arrayNode('cache')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('pool')
                            ->defaultValue('cache.app')
                            ->info('Cache pool service to use for tenant settings')
                        ->end()
                        ->integerNode('ttl')
                            ->defaultValue(3600)
                            ->min(0)
                            ->info('Cache TTL in seconds for tenant settings')
                        ->end()
                    ->end()
                ->end()

                // Mailer configuration
                ->arrayNode('mailer')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable tenant-aware mailer configuration')
                        ->end()
                        ->booleanNode('add_tenant_id_header')
                            ->defaultFalse()
                            ->info('Opt in to the public X-Tenant-ID email header')
                        ->end()
                        ->booleanNode('add_tenant_name_header')
                            ->defaultFalse()
                            ->info('Opt in to the public X-Tenant-Name email header independently')
                        ->end()
                        ->scalarNode('fallback_dsn')
                            ->defaultNull()
                            ->info('Fallback mailer DSN when tenant has no specific configuration')
                        ->end()
                        ->scalarNode('fallback_from')
                            ->defaultNull()
                            ->info('Fallback from address when tenant has no specific configuration')
                        ->end()
                        ->scalarNode('fallback_sender')
                            ->defaultNull()
                            ->info('Fallback sender name when tenant has no specific configuration')
                        ->end()
                    ->end()
                ->end()

                // Messenger configuration
                ->arrayNode('messenger')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable tenant-aware messenger configuration')
                        ->end()
                        ->scalarNode('fallback_dsn')
                            ->defaultValue('sync://')
                            ->info('Fallback messenger transport DSN when tenant has no specific configuration')
                        ->end()
                        ->scalarNode('fallback_bus')
                            ->defaultValue('messenger.bus.default')
                            ->info('Fallback messenger bus when tenant has no specific configuration')
                        ->end()
                        ->scalarNode('default_transport')
                            ->defaultValue('async')
                            ->info('Default transport name when no tenant-specific mapping exists')
                        ->end()
                        ->enumNode('routing_strategy')
                            ->values(array_map(static fn (MessengerRoutingStrategy $strategy): string => $strategy->value, MessengerRoutingStrategy::cases()))
                            ->defaultValue(MessengerRoutingStrategy::TENANT_TRANSPORT->value)
                            ->info('Choose tenant-specific transport selection or native Symfony Messenger routing')
                        ->end()
                        ->booleanNode('add_tenant_headers')
                            ->defaultTrue()
                            ->info('Add tenant information to message headers/stamps')
                        ->end()
                        ->arrayNode('tenant_transport_map')
                            ->useAttributeAsKey('tenant_slug')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                            ->info('Mapping of tenant slugs to transport names')
                        ->end()
                    ->end()
                ->end()

                // Fixtures configuration
                ->arrayNode('fixtures')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable tenant-aware fixtures loading')
                        ->end()
                    ->end()
                ->end()

                // Events configuration
                ->arrayNode('events')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('dispatch_database_switch')
                            ->defaultTrue()
                            ->info('Dispatch events when switching tenant databases')
                        ->end()
                    ->end()
                ->end()

                // Storage configuration
                ->arrayNode('storage')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable tenant-aware file storage')
                        ->end()
                        ->enumNode('type')
                            ->values(['local', 's3', 'custom'])
                            ->defaultValue('local')
                            ->info('Storage type to use')
                        ->end()
                        ->arrayNode('local')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('base_path')
                                    ->defaultValue('%kernel.project_dir%/var/storage')
                                    ->info('Base path for local storage')
                                ->end()
                                ->scalarNode('base_url')
                                    ->defaultValue('/uploads')
                                    ->info('Base URL for accessing stored files')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('s3')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('bucket')
                                    ->defaultNull()
                                    ->info('S3 bucket name')
                                ->end()
                                ->scalarNode('region')
                                    ->defaultValue('us-east-1')
                                    ->info('S3 region')
                                ->end()
                                ->scalarNode('base_url')
                                    ->defaultNull()
                                    ->info('Base URL for S3 files (CloudFront, etc.)')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                ->append(ObjectStorageConfiguration::node())

                // Container scoping configuration
                ->arrayNode('container')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enable_tenant_scope')
                            ->defaultFalse()
                            ->info('Enable tenant-scoped services in the container')
                        ->end()
                    ->end()
                ->end()

                // Event listeners configuration
                ->arrayNode('listeners')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('request_listener')
                            ->defaultTrue()
                            ->info('Enable automatic tenant resolution from requests')
                        ->end()
                        ->booleanNode('doctrine_filter_listener')
                            ->defaultTrue()
                            ->info('Enable automatic Doctrine filter configuration')
                        ->end()
                    ->end()
                ->end()

                // Decorators configuration
                ->arrayNode('decorators')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('cache')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                    ->info('Enable tenant-aware cache decorators (PSR-6 and PSR-16)')
                                ->end()
                                ->arrayNode('services')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['cache.app'])
                                    ->info('List of cache service IDs to decorate')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('logger')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                    ->info('Enable tenant-aware logger processor')
                                ->end()
                                ->arrayNode('channels')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['app'])
                                    ->info('List of logger channels to add tenant processor to')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('storage')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                    ->info('Enable tenant-aware storage path helper')
                                ->end()
                                ->booleanNode('use_slug')
                                    ->defaultFalse()
                                    ->info('Use tenant slug instead of ID for path prefixing')
                                ->end()
                                ->scalarNode('path_separator')
                                    ->defaultValue('/')
                                    ->info('Path separator to use for tenant directories')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
