<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260831000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the exact consumer compatibility fixture tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tenant (id VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CONSUMER_TENANT_SLUG ON tenant (slug)');
        $this->addSql('CREATE TABLE consumer_global_records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE consumer_tenant_records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(255) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CONSUMER_TENANT_RECORD ON consumer_tenant_records (tenant_id)');
        $this->addSql('ALTER TABLE consumer_tenant_records ADD CONSTRAINT FK_CONSUMER_TENANT_RECORD FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE consumer_tenant_records');
        $this->addSql('DROP TABLE consumer_global_records');
        $this->addSql('DROP TABLE tenant');
    }
}
